services:

  weather_requester2:
    build: .
    #container_name: weather_requester
    environment:
      - LOCATION=2178
      - MQTT_BROKER=167.172.164.168
      - MQTT_PORT=1883
      - MQTT_TOPIC=261833/Del_Norte  # Nazwa pliku
      - MQTT_USERNAME=student  # Użytkownik
      - MQTT_PASSWORD=sys-wbud  # Hasło
      - WEATHER_REQUESTER=weather_requester.py
      - WEATHER_ENV=development
    # volumes:
    #   - .:/app
    ports:
      - "5678:5678"
    #command: ["python", "weather_requester.py"]
    command: ["python", "tmp.py"]

  flask_app:
    build: .
    container_name: flask_domain
    ports:
      - "9361:9361"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
    command: ["python", "main.py"]
    depends_on:
      - weather_requester2

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9361"]
      interval: 30s
      retries: 3
